services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=64M --innodb-log-file-size=16M --innodb-log-buffer-size=8M --innodb-ft-total-cache-size=32M --innodb-ft-cache-size=1M --max-connections=20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Complex_Root_Pass_2025!}
      MYSQL_DATABASE: maltalist
      MYSQL_USER: maltalist_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-M@LtApass_Secure_2025!}
    volumes:
      - ./files/backups:/backups
      - ./files/backups/backup.sh:/backup.sh
      - mysql_data:/var/lib/mysql
      - ./maltalist-api/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 224M
        reservations:
          cpus: '0.1'
          memory: 128M
  
  api:
    build:
      context: ./maltalist-api
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "5023:5023"
      - "7004:7004"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=maltalist;User=maltalist_user;Password=${MYSQL_PASSWORD:-M@LtApass_Secure_2025!};
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 264M
        reservations:
          cpus: '0.05'
          memory: 32M
    volumes:
      - ./files/images:/images

  ui:
    build:
      context: ./maltalist-angular
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./files/images:/usr/share/nginx/html/assets/img/listings
      - ./maltalist-angular/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M

  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-M@LtApass_Secure_2025!}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files/stats:/var/www/html/stats
    depends_on:
      - api
      - db
      - ui
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 64M
        reservations:
          cpus: '0.02'
          memory: 10M

volumes:
  mysql_data: